// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Two Wells <contact@twowells.dev>

//! Committed scipy/numpy golden reference vectors for `OmniDSP`.
//!
//! This crate is the **single source of truth** for the reference data that the
//! `omnidsp-core` tests and the [`omnidsp-conformance`] suite check against
//! (ADR-007 §3).  It is a leaf crate with no dependencies: every module is a
//! file of `pub const` arrays generated by the committed scripts in `scripts/`
//! (regenerate with `make gen-*-reference`).
//!
//! Keeping the data here — rather than inside `omnidsp-core` — breaks the
//! `core → conformance` dependency cycle: the conformance suite depends on
//! core, so core cannot depend on conformance, but both can depend on this
//! third crate.  `omnidsp-core` pulls it in as a **dev-dependency**;
//! `omnidsp-conformance` pulls it in as a normal dependency.
//!
//! Complex reference values are stored as `(re, im)` `f64` tuples so that this
//! crate needs no `num-complex` dependency; consumers map them into whatever
//! complex type they use.
//!
//! [`omnidsp-conformance`]: https://github.com/TwoWells/OmniDSP

#![allow(
    missing_docs,
    reason = "bulk machine-generated numeric reference vectors; per-const docs would be noise"
)]

pub mod cqt_librosa;
pub mod cqt_numpy;
pub mod cqt_process_numpy;
pub mod dct_scipy;
pub mod fir_lfilter_scipy;
pub mod fir_scipy;
pub mod hilbert_scipy;
pub mod iir_scipy;
pub mod iir_sosfilt_scipy;
pub mod resample_poly_scipy;
pub mod resample_scipy;
pub mod xcorr_scipy;
