/**
 * @file omnidsp.cpp
 * @brief Implements the non-template OmniDSP class methods (factory,
 * constructor, etc.). Template method definitions are in omnidsp.hpp.
 * Uses if constexpr for backend selection logic within the factory.
 * Exception handling uses OmniExpected<T, Status>.
 * Uses AbstractBackend interface from OmniDSP::abstract namespace.
 */

// Corresponding header (Declares OmniDSP class, OmniExpected, Status, Backend
// etc.)
#include <OmniDSP/omnidsp.hpp>  // Includes core_types.hpp

// Include the backend interface definition (declares AbstractBackend and
// backend factory functions in OmniDSP::abstract namespace)
#include "interface/backend.hpp"  // Defines OmniDSP::abstract::AbstractBackend and factory functions

// Include the generated configuration header which defines
// OMNIDSP_BACKEND__ENABLED* macros used for conditional compilation.
// Ensure this file is correctly generated by your build system (e.g., CMake).
#include <OmniDSP/omnidsp_config.hpp>  // Contains OMNIDSP_BACKEND__ENABLED* defines

// Include backend headers needed for their factory functions using #if
// because if constexpr cannot be used at file scope for includes.
// These headers should *define* the factory functions declared in
// interface/backend.hpp
#include "default/backend.hpp"  // Defines abstract::create_default_backend

#if OMNIDSP_BACKEND_ACCELERATE_ENABLED
#pragma message("Accelerate backend enabled.")  // Compile-time message
#include "accelerate/backend.hpp"  // Defines abstract::create_accelerate_backend
#endif
#if OMNIDSP_BACKEND_ONEMKL_ENABLED
#pragma message("OneMKL backend enabled.")  // Compile-time message
#include "onemkl/backend.hpp"  // Defines abstract::create_onemkl_backend
#endif
#if OMNIDSP_BACKEND_INTELIPP_ENABLED
#pragma message("IntelIPP backend enabled.")  // Compile-time message
#include "intelipp/backend.hpp"  // Defines abstract::create_intelipp_backend
#endif

// Standard Library Includes
#include <exception>  // For std::exception, std::bad_alloc
#include <expected>   // For std::unexpected (used with OmniExpected)
#include <iostream>   // For std::cerr, std::endl, std::cout
#include <memory>     // For std::unique_ptr
#include <stdexcept>  // For std::runtime_error (used in get_backend, base for OmniDSPException)
#include <utility>  // For std::move, std::unexpect
#include <vector>   // Example include, might not be directly needed here

// Assuming OmniDSPException is defined, potentially in core_types.hpp or
// omnidsp.hpp #include <OmniDSP/core_types.hpp> // Ensure OmniDSPException is
// defined

namespace OmniDSP {

  //--------------------------------------------------------------------------
  // OmniDSP Method Definitions (Non-Template)
  //--------------------------------------------------------------------------

  // --- Factory Function ---
  /**
   * @brief Factory function to create an OmniDSP instance with a specific
   * backend.
   * @param backend The desired backend implementation (OmniDSP::Backend enum).
   * @return An OmniExpected containing the OmniDSP instance on success, or a
   * Status code on failure.
   */
  // Definition matches declaration: static OmniExpected<OmniDSP> create(Backend
  // backend); Default argument is only in the declaration.
  [[nodiscard]] /* static */ OmniExpected<OmniDSP> OmniDSP::create(
      BackendType backend)
  {
    // Pointer to the abstract backend implementation (using type from
    // interface/backend.hpp)
    std::unique_ptr<Abstract::Backend> pimpl = nullptr;

    try {
      // Select the backend factory based on the requested type and availability
      switch (backend) {  // Switching on the 'Backend' enum parameter
        case BackendType::Accelerate:  // Use 'Backend' enum value
          // Use if constexpr to check if the backend is enabled at compile time
          if constexpr (OMNIDSP_BACKEND_ACCELERATE_ENABLED) {
            std::cout << "Creating Accelerate backend..." << std::endl;
            // Call factory function from abstract namespace
            pimpl = Abstract::create_accelerate_backend();
            if (!pimpl) {  // Check if factory succeeded at runtime
              std::cerr << "Error: Accelerate backend factory failed."
                        << std::endl;
              return std::unexpected(Status::BackendError);
            }
          }
          else {
            std::cerr
                << "Error: Accelerate backend requested but not compiled in."
                << std::endl;
            return std::unexpected(Status::UnsupportedFeature);
          }
          break;  // End Accelerate case

        case BackendType::OneMKL:  // Use 'Backend' enum value
          if constexpr (OMNIDSP_BACKEND_ONEMKL_ENABLED) {
            std::cout << "Creating OneMKL backend..." << std::endl;
            // Call factory function from abstract namespace
            pimpl = Abstract::create_onemkl_backend();
            if (!pimpl) {
              std::cerr << "Error: OneMKL backend factory failed." << std::endl;
              return std::unexpected(Status::BackendError);
            }
          }
          else {
            std::cerr << "Error: oneMKL backend requested but not compiled in."
                      << std::endl;
            return std::unexpected(Status::UnsupportedFeature);
          }
          break;  // End OneMKL case

        case BackendType::IntelIPP:  // Use 'Backend' enum value
          if constexpr (OMNIDSP_BACKEND_INTELIPP_ENABLED) {
            std::cout << "Creating IntelIPP backend..." << std::endl;
            // Call factory function from abstract namespace
            pimpl = Abstract::create_intelipp_backend();
            if (!pimpl) {
              std::cerr << "Error: IntelIPP backend factory failed."
                        << std::endl;
              return std::unexpected(Status::BackendError);
            }
          }
          else {
            std::cerr
                << "Error: IntelIPP backend requested but not compiled in."
                << std::endl;
            return std::unexpected(Status::UnsupportedFeature);
          }
          break;  // End IntelIPP case

        case BackendType::Default:  // Use 'Backend' enum value
        default:                    // Fallback to Default
          // Default backend should ideally always be enabled
          if constexpr (OMNIDSP_BACKEND_DEFAULT_ENABLED) {
            std::cout << "Creating Default backend..." << std::endl;
            // Call factory function from abstract namespace
            pimpl = Abstract::create_default_backend();
            if (!pimpl) {
              std::cerr << "Error: Default backend factory failed."
                        << std::endl;
              return std::unexpected(Status::BackendError);
            }
          }
          else {
            // This indicates a build system configuration error
            std::cerr << "Error: Default backend requested but not compiled in "
                         "(OMNIDSP_BACKEND_DEFAULT_ENABLED is false)."
                      << std::endl;
            return std::unexpected(Status::BackendError);
          }
          break;  // End Default case
      }  // End switch

      // If we fall through the switch without returning an error, pimpl should
      // be valid.
      if (!pimpl) {
        // This case should ideally not be reached if all factories are checked
        std::cerr << "Internal Error: Backend selection failed unexpectedly."
                  << std::endl;
        return std::unexpected(Status::Failure);
      }

      std::cout
          << "Backend created successfully. Constructing OmniDSP instance."
          << std::endl;

      // Use private constructor (takes unique_ptr<abstract::AbstractBackend>)
      OmniDSP dsp_instance(std::move(pimpl));

      // Return the successfully created instance wrapped in OmniExpected
      return dsp_instance;
    }
    // Catch specific exceptions first if they map to specific Status codes
    catch (const std::bad_alloc &e) {
      std::cerr << "Error: Memory allocation failed during backend creation: "
                << e.what() << std::endl;
      return std::unexpected(Status::AllocationError);
    }
    // Catch any other std::exception (including derived classes like
    // std::runtime_error and potentially OmniDSPException if it inherits from
    // it)
    catch (const std::exception &e) {
      // Log the actual error message from the exception
      std::cerr << "Error: Exception during backend initialization: "
                << e.what() << std::endl;
      // Return a general backend error status
      return std::unexpected(Status::BackendError);
    }
    // Catch any other unknown exceptions (non-std::exception based)
    catch (...) {
      std::cerr << "Error: Unknown exception during backend creation."
                << std::endl;
      return std::unexpected(
          Status::Failure);  // Generic failure for unknown errors
    }
  }

  // --- Constructor / Destructor / Move Operations ---

  // Private constructor taking the backend implementation pointer
  // Definition matches declaration:
  // OmniDSP(std::unique_ptr<abstract::AbstractBackend> impl);
  OmniDSP::OmniDSP(std::unique_ptr<Abstract::Backend> impl)
      : pimpl_(std::move(impl))
  {
    if (!pimpl_) {
      // Throw here because constructing with null is a programming error
      throw std::runtime_error(
          "OmniDSP constructed with null implementation pointer.");
    }
    // Optional: Add logging if desired
    // std::cout << "OmniDSP instance constructed with backend: "
    //           << get_backend_name(pimpl_->get_backend()) // Call
    //           get_backend() from interface
    //           << std::endl;
  }

  // Destructor needs to be defined (even if default) because of unique_ptr to
  // incomplete type
  OmniDSP::~OmniDSP() = default;  // Definition required here

  // Move constructor - definition matches declaration
  OmniDSP::OmniDSP(OmniDSP &&other) noexcept = default;

  // Move assignment operator - definition matches declaration
  OmniDSP &OmniDSP::operator=(OmniDSP &&other) noexcept = default;

  // --- Public Member Functions (Non-Template) ---

  /**
   * @brief Gets the type of the backend currently used by this OmniDSP
   * instance.
   * @return The Backend enum value.
   * @throws std::runtime_error if the instance is in an invalid (e.g.,
   * moved-from) state.
   */
  // Definition matches declaration: Backend get_backend() const;
  BackendType OmniDSP::get_backend() const
  {
    if (!pimpl_) {
      // Throw here as using a moved-from object is a programming error
      throw std::runtime_error(
          "Invalid OmniDSP instance in get_backend (possibly moved-from).");
    }
    // Call the get_backend() method from the AbstractBackend interface.
    return pimpl_->get_backend();
  }

}  // namespace OmniDSP
