/**
 * @file cqt.hpp (default)
 * @brief Declares the concrete CQTPlanImpl class for the Default backend.
 */

#ifndef OMNIDSP_DEFAULT_CQT_HPP
#define OMNIDSP_DEFAULT_CQT_HPP

#include <OmniDSP/core_types.hpp>  // Status, F32, F64, C32, C64, Detail::*
#include <OmniDSP/fft.hpp>         // Needed for FFTPlan interface
#include <OmniDSP/resample.hpp>    // Needed for ResamplePlan interface
#include <OmniDSP/window.hpp>      // Non-templated WindowSpec
#include <complex>
#include <cstddef>  // For size_t
#include <memory>   // For std::unique_ptr
#include <span>     // For std::span
#include <vector>

#include "../interface/backend.hpp"  // Base CQTPlanImpl interface and AbstractBackend

namespace OmniDSP::backend {
  /**
   * @brief Default backend implementation for a Constant-Q Transform (CQT)
   * Plan.
   * @tparam T The REAL data type (F32 or F64).
   */
  template <typename T>  // T is real type (F32, F64)
  class DefaultCQTPlanImpl final : public CQTPlanImpl<T> {
   public:
    using Real = T;                          // Alias for clarity
    using Complex = Detail::GetComplexT<T>;  // Use type trait

    /**
     * @brief Constructs a DefaultCQTPlanImpl.
     * @param owner Pointer to the backend instance creating this plan (needed
     * for internal helpers like window generation and sub-plan creation).
     * @param sample_rate The sample rate of the input signal.
     * @param min_freq The minimum frequency for the CQT bins.
     * @param max_freq The maximum frequency for the CQT bins.
     * @param bins_per_octave The number of frequency bins per octave.
     * @param window_spec Specification for the window function to use for
     * spectral analysis.
     * @throws std::invalid_argument if parameters are invalid (e.g.,
     * sample_rate <= 0, min_freq <= 0, max_freq <= min_freq).
     * @throws std::runtime_error if internal setup (e.g., FFT plan creation,
     * kernel generation) fails.
     */
    DefaultCQTPlanImpl(
        const AbstractBackend* owner,  // Use AbstractBackend
        Real sample_rate,
        Real min_freq,
        Real max_freq,
        int bins_per_octave,
        const WindowSpec& window_spec);  // Use non-templated WindowSpec

    /**
     * @brief Destructor.
     */
    ~DefaultCQTPlanImpl() override;

    // --- Disable Copy/Move ---
    DefaultCQTPlanImpl(const DefaultCQTPlanImpl&) = delete;
    DefaultCQTPlanImpl& operator=(const DefaultCQTPlanImpl&) = delete;
    DefaultCQTPlanImpl(DefaultCQTPlanImpl&&) = delete;
    DefaultCQTPlanImpl& operator=(DefaultCQTPlanImpl&&) = delete;

    // --- Interface Methods Implementation ---

    /**
     * @brief Executes the CQT calculation on the input signal.
     * @param input A span representing the real input signal.
     * @param output A span representing the complex output buffer (CQT
     * coefficients). The size should be num_bins *
     * num_output_frames(input.size()).
     * @return Status indicating success or failure.
     */
    [[nodiscard]] Status execute(
        std::span<const Real> input, std::span<Complex> output) const override;

    /**
     * @brief Gets the number of frequency bins generated by the CQT.
     * @return The number of bins.
     */
    size_t get_num_bins() const override;

    /**
     * @brief Calculates the number of output time frames for a given input
     * length.
     * @param input_length Length of the input signal in samples.
     * @return The number of output frames.
     */
    size_t get_num_output_frames(size_t input_length) const override;

    /**
     * @brief Gets the hop length (step size) between consecutive CQT frames in
     * samples.
     * @return The hop length.
     */
    size_t get_hop_length() const override;

    // --- Optional: Add getters for other parameters if needed ---
    // T get_sample_rate() const;
    // T get_min_frequency() const;
    // T get_max_frequency() const;
    // int get_bins_per_octave() const;

   private:
    // --- Configuration ---
    const AbstractBackend* owner_;  // Non-owning pointer to backend for helpers
    Real sample_rate_;
    Real min_freq_;
    Real max_freq_;
    int bins_per_octave_;
    WindowSpec window_spec_;
    Real quality_factor_;  // *** ADDED ***
    size_t num_bins_;
    size_t hop_length_;
    size_t
        fft_length_;  // *** ADDED: Store the calculated overall FFT length ***
    std::vector<Real>
        center_frequencies_;              // *** RENAMED from center_freqs_ ***
    std::vector<size_t> kernel_lengths_;  // *** ADDED ***

    // --- Precomputed Data / Internal Plans ---
    std::vector<std::vector<Complex>>
        kernels_fft_;  // *** RENAMED from spectral_kernels_fft_ ***
    std::unique_ptr<FFTPlan<Complex>>
        fft_plan_;  // *** CHANGED from vector fft_plans_ ***
    std::unique_ptr<ResamplePlan<Real>> resample_plan_;  // *** ADDED ***

    // Helper methods for setup (can remain private)
    // void calculate_parameters(); // Integrated into constructor
    // void precompute_kernels(); // Integrated into constructor
  };

  // --- Explicit Template Instantiations (Declaration) ---
  extern template class DefaultCQTPlanImpl<F32>;
  extern template class DefaultCQTPlanImpl<F64>;

}  // namespace OmniDSP::backend

#endif  // OMNIDSP_DEFAULT_CQT_HPP
