#!/usr/bin/env python3
"""Generate numpy reference data for CQT module process tests.

Computes CQT coefficients using the same algorithm as the Rust
implementation: frequency-domain kernel correlation with 1/N scaling.

Outputs a Rust source file with const arrays of input signals and
expected complex CQT coefficients.

Regenerate with: make gen-cqt-process-reference

Requires: numpy, scipy
"""

import sys
from math import ceil

import numpy as np
from scipy.signal.windows import hann


def design_cqt(sample_rate, min_freq, max_freq, bins_per_octave):
    """Design CQT parameters matching the Rust implementation."""
    b = bins_per_octave
    nyquist = sample_rate / 2.0
    q = 1.0 / (2.0 ** (1.0 / b) - 1.0)

    freqs = []
    kernel_lengths = []
    k = 0
    while True:
        freq = min_freq * 2.0 ** (k / b)
        if freq >= max_freq or freq >= nyquist:
            break
        kernel_len = max(1, int(ceil(q * sample_rate / freq)))
        freqs.append(freq)
        kernel_lengths.append(kernel_len)
        k += 1

    max_kernel = kernel_lengths[0]
    fft_length = 1 << int(ceil(np.log2(max_kernel))) if max_kernel > 0 else 1

    return q, freqs, kernel_lengths, fft_length


def compute_cqt(signal, sample_rate, freqs, kernel_lengths, fft_length):
    """Compute CQT coefficients matching the Rust frequency-domain algorithm.

    For each bin:
      1. Build time-domain kernel: (1/N_k) * window[n] * exp(j*2pi*f_k*n/sr)
      2. Zero-pad to fft_length
      3. FFT (unnormalized)
      4. Store conj(K) / fft_length

    Processing:
      1. FFT(input) (unnormalized)
      2. For each bin: sum(X * stored_kernel)
    """
    n = fft_length
    # numpy.fft.fft uses X[k] = sum_n x[n] * exp(-j*2pi*k*n/N)
    # which matches our DftNorm::None forward FFT.
    x_padded = np.zeros(n)
    x_padded[: len(signal)] = signal
    X = np.fft.fft(x_padded)

    coeffs = []
    for freq, klen in zip(freqs, kernel_lengths):
        # Hann window matching Rust: 0.5*(1 - cos(2*pi*i/(N-1)))
        w = hann(klen, sym=True)

        # Time-domain kernel
        inv_nk = 1.0 / klen
        kernel = np.zeros(n, dtype=complex)
        for i in range(klen):
            angle = 2.0 * np.pi * freq * i / sample_rate
            kernel[i] = inv_nk * w[i] * np.exp(1j * angle)

        # FFT of kernel (unnormalized)
        K = np.fft.fft(kernel)

        # Stored kernel: conj(K) / N
        stored = np.conj(K) / n

        # CQT coefficient: sum(X * stored)
        coeff = np.sum(X * stored)
        coeffs.append(coeff)

    return np.array(coeffs)


def format_f64(val):
    return f"{val:.17e}"


def write_real_array(out, name, doc, values):
    out.write(f"/// {doc}\n")
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write('    reason = "numpy reference"\n')
    out.write(")]\n")
    out.write(f"const {name}: &[f64] = &[\n")
    for v in values:
        out.write(f"    {format_f64(v)},\n")
    out.write("];\n\n")


def write_complex_array(out, name, doc, values):
    out.write(f"/// {doc}\n")
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write('    reason = "numpy reference"\n')
    out.write(")]\n")
    out.write(f"const {name}: &[(f64, f64)] = &[\n")
    for v in values:
        out.write(f"    ({format_f64(v.real)}, {format_f64(v.imag)}),\n")
    out.write("];\n\n")


def main():
    out = sys.stdout

    sr = 44100.0
    min_freq = 440.0
    max_freq = 880.0
    bpo = 12

    q, freqs, kernel_lengths, fft_length = design_cqt(sr, min_freq, max_freq, bpo)

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_cqt_process_reference.py\n")
    out.write("// Regenerate: make gen-cqt-process-reference\n")
    out.write("//\n")
    out.write(f"// numpy {np.__version__}, scipy {__import__('scipy').__version__}\n")
    out.write("//\n")
    out.write(f"// CQT: sr={sr}, fmin={min_freq}, fmax={max_freq}, B={bpo}\n")
    out.write(f"// Q={q:.10f}, {len(freqs)} bins, fft_length={fft_length}\n")
    out.write("\n")

    out.write(f"const CQT_PROC_SAMPLE_RATE: f64 = {sr};\n")
    out.write(f"const CQT_PROC_MIN_FREQ: f64 = {min_freq};\n")
    out.write(f"const CQT_PROC_MAX_FREQ: f64 = {max_freq};\n")
    out.write(f"const CQT_PROC_BINS_PER_OCTAVE: u32 = {bpo};\n")
    out.write(f"const CQT_PROC_FFT_LENGTH: usize = {fft_length};\n")
    out.write(f"const CQT_PROC_NUM_BINS: usize = {len(freqs)};\n")
    out.write("\n")

    t = np.arange(fft_length) / sr

    # --- Case 1: Sum of all bin frequencies — every bin responds ---
    all_tones = np.zeros(fft_length)
    for freq in freqs:
        all_tones += np.sin(2.0 * np.pi * freq * t)
    all_tones_cqt = compute_cqt(all_tones, sr, freqs, kernel_lengths, fft_length)

    write_real_array(
        out,
        "CQT_PROC_ALL_TONES_INPUT",
        f"Sum of {len(freqs)} sines at all bin center frequencies",
        all_tones,
    )
    write_complex_array(
        out,
        "CQT_PROC_ALL_TONES_OUTPUT",
        "CQT of all-tones signal — every bin responds",
        all_tones_cqt,
    )

    # --- Case 2: Pure tone at the middle bin's center frequency ---
    mid_bin = len(freqs) // 2
    tone_freq = freqs[mid_bin]
    tone = np.sin(2.0 * np.pi * tone_freq * t)
    tone_cqt = compute_cqt(tone, sr, freqs, kernel_lengths, fft_length)

    write_real_array(
        out,
        "CQT_PROC_TONE_INPUT",
        f"Pure sine at {tone_freq:.6f} Hz (bin {mid_bin})",
        tone,
    )
    write_complex_array(
        out,
        "CQT_PROC_TONE_OUTPUT",
        f"CQT of sine at bin {mid_bin} center frequency",
        tone_cqt,
    )
    out.write(f"const CQT_PROC_TONE_BIN: usize = {mid_bin};\n\n")

    # --- Case 3: Sum of two tones at bin 2 and bin 9 ---
    freq_a = freqs[2]
    freq_b = freqs[9]
    two_tone = np.sin(2.0 * np.pi * freq_a * t) + np.sin(2.0 * np.pi * freq_b * t)
    two_tone_cqt = compute_cqt(two_tone, sr, freqs, kernel_lengths, fft_length)

    write_real_array(
        out,
        "CQT_PROC_TWO_TONE_INPUT",
        f"Two sines at {freq_a:.6f} Hz (bin 2) and {freq_b:.6f} Hz (bin 9)",
        two_tone,
    )
    write_complex_array(
        out,
        "CQT_PROC_TWO_TONE_OUTPUT",
        "CQT of two-tone signal",
        two_tone_cqt,
    )


if __name__ == "__main__":
    main()
