#!/usr/bin/env python3
"""Generate scipy reference data for FIR windowed-sinc tests.

Outputs a Rust source file with const arrays of FIR tap coefficients.
Regenerate with: make gen-fir-reference

Requires: scipy, numpy
"""

import sys

import numpy as np
from scipy.signal import firwin

# (name, numtaps, cutoff, window, pass_zero, fs)
# numtaps = order + 1
CASES = [
    # Lowpass
    ("LP_ORDER30_HAMMING", 31, 1000, "hamming", True, 44100),
    # Highpass
    ("HP_ORDER30_HANN", 31, 10000, "hann", False, 44100),
    # Bandpass
    ("BP_ORDER60_HAMMING", 61, [1000, 5000], "hamming", False, 44100),
    # Bandstop
    ("BS_ORDER60_HAMMING", 61, [1000, 5000], "hamming", True, 44100),
    # Pure sinc (rectangular window)
    ("LP_ORDER4_RECT", 5, 0.25, "boxcar", True, 2),
]


def format_coeff(val):
    """Format one coefficient as a Rust f64 literal."""
    return f"    {val:.17e},"


def main():
    out = sys.stdout

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_fir_reference.py\n")
    out.write("// Regenerate: make gen-fir-reference\n")
    out.write("//\n")
    out.write(f"// scipy {__import__('scipy').__version__}, ")
    out.write(f"numpy {np.__version__}\n")
    out.write("\n")

    for name, numtaps, cutoff, window, pass_zero, fs in CASES:
        taps = firwin(numtaps, cutoff, window=window, pass_zero=pass_zero, fs=fs)

        cutoff_str = str(cutoff)
        out.write(f"/// `firwin({numtaps}, {cutoff_str}, window='{window}', ")
        out.write(f"pass_zero={pass_zero}, fs={fs})`\n")
        out.write("#[allow(\n")
        out.write("    clippy::excessive_precision,\n")
        out.write("    clippy::unreadable_literal,\n")
        out.write("    reason = \"scipy reference\"\n")
        out.write(")]\n")
        out.write(f"pub const {name}: &[f64] = &[\n")
        for coeff in taps:
            out.write(format_coeff(coeff) + "\n")
        out.write("];\n\n")


if __name__ == "__main__":
    main()
