#!/usr/bin/env python3
"""Generate scipy reference data for IIR Butterworth tests.

Outputs a Rust source file with const arrays of SOS coefficients.
Regenerate with: make gen-iir-reference

Requires: scipy, numpy
"""

import sys
from scipy.signal import butter

# (name, order, btype, freq_args, fs)
CASES = [
    # Lowpass
    ("LP_ORDER1", 1, "low",      1000,             44100),
    ("LP_ORDER2", 2, "low",      1000,             44100),
    ("LP_ORDER4", 4, "low",      1000,             44100),
    ("LP_ORDER8", 8, "low",      1000,             44100),
    # Highpass
    ("HP_ORDER2", 2, "high",     10000,            44100),
    ("HP_ORDER4", 4, "high",     10000,            44100),
    # Bandpass
    ("BP_ORDER2", 2, "band",     [1000, 5000],     44100),
    ("BP_ORDER4", 4, "band",     [1000, 5000],     44100),
    # Bandstop
    ("BS_ORDER2", 2, "bandstop", [1000, 5000],     44100),
    ("BS_ORDER4", 4, "bandstop", [1000, 5000],     44100),
]

def format_section(row):
    """Format one SOS row [b0, b1, b2, a0, a1, a2] as a Rust tuple."""
    b0, b1, b2, _a0, a1, a2 = row
    return f"    ({b0:.17e}, {b1:.17e}, {b2:.17e}, {a1:.17e}, {a2:.17e}),"

def main():
    out = sys.stdout

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_iir_reference.py\n")
    out.write("// Regenerate: make gen-iir-reference\n")
    out.write("//\n")
    out.write(f"// scipy {__import__('scipy').__version__}, ")
    out.write(f"numpy {__import__('numpy').__version__}\n")
    out.write("\n")
    out.write("// Each entry is (b0, b1, b2, a1, a2) with a0=1 omitted.\n")
    out.write("// Section order matches scipy's zpk2sos default pairing.\n")
    out.write("\n")

    for name, order, btype, freq, fs in CASES:
        sos = butter(order, freq, btype=btype, fs=fs, output="sos")
        assert sos is not None
        freq_str = str(freq)
        out.write(f"/// `butter({order}, {freq_str}, '{btype}', fs={fs})`\n")
        out.write("#[allow(\n")
        out.write("    clippy::excessive_precision,\n")
        out.write("    clippy::unreadable_literal,\n")
        out.write("    reason = \"scipy reference\"\n")
        out.write(")]\n")
        out.write(f"const {name}: &[(f64, f64, f64, f64, f64)] = &[\n")
        for row in sos:
            out.write(format_section(row) + "\n")
        out.write("];\n\n")

if __name__ == "__main__":
    main()
