#!/usr/bin/env python3
"""Generate scipy reference data for IIR streaming filter (sosfilt) tests.

Uses scipy.signal.sosfilt to produce expected output for known inputs
filtered through Butterworth biquad cascades.

Outputs a Rust source file with const arrays of SOS coefficients, input
signals, and expected outputs.

Regenerate with: make gen-iir-sosfilt-reference

Requires: scipy, numpy
"""

import sys

import numpy as np
from scipy.signal import butter, sosfilt


def format_value(val):
    """Format one value as a Rust f64 literal."""
    return f"    {val:.17e},"


def format_section(row):
    """Format one SOS row [b0, b1, b2, a0, a1, a2] as a Rust tuple."""
    b0, b1, b2, _a0, a1, a2 = row
    return f"    ({b0:.17e}, {b1:.17e}, {b2:.17e}, {a1:.17e}, {a2:.17e}),"


def write_array(out, name, doc, values):
    """Write a const f64 array to the output."""
    out.write(f"/// `{doc}`\n")
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write('    reason = "scipy reference"\n')
    out.write(")]\n")
    out.write(f"const {name}: &[f64] = &[\n")
    for v in values:
        out.write(format_value(v) + "\n")
    out.write("];\n\n")


def write_sos(out, name, doc, sos):
    """Write a const SOS array to the output."""
    out.write(f"/// `{doc}`\n")
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write('    reason = "scipy reference"\n')
    out.write(")]\n")
    out.write(f"const {name}: &[(f64, f64, f64, f64, f64)] = &[\n")
    for row in sos:
        out.write(format_section(row) + "\n")
    out.write("];\n\n")


def main():
    out = sys.stdout
    fs = 44100.0

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_iir_sosfilt_reference.py\n")
    out.write("// Regenerate: make gen-iir-sosfilt-reference\n")
    out.write("//\n")
    out.write(f"// scipy {__import__('scipy').__version__}, ")
    out.write(f"numpy {np.__version__}\n")
    out.write("\n")

    # --- Deterministic input signal ---
    # Mix of sinusoids spanning low and high frequencies.
    n_samples = 256
    t = np.arange(n_samples) / fs
    signal = np.sin(2 * np.pi * 400 * t) + 0.5 * np.sin(2 * np.pi * 8000 * t)
    write_array(
        out, "SOSFILT_INPUT",
        f"{n_samples} samples: sin(400 Hz) + 0.5*sin(8000 Hz) at {fs:.0f} Hz",
        signal,
    )

    # --- Case 1: Lowpass Butterworth order 4, fc=1000 Hz ---
    lp4_sos = butter(4, 1000, btype="low", fs=fs, output="sos")
    lp4_output = sosfilt(lp4_sos, signal)
    write_sos(out, "SOSFILT_LP4_SOS", "butter(4, 1000, 'low', fs=44100)", lp4_sos)
    write_array(out, "SOSFILT_LP4_OUTPUT", "sosfilt(lp4_sos, signal)", lp4_output)

    # --- Case 2: Highpass Butterworth order 4, fc=5000 Hz ---
    hp4_sos = butter(4, 5000, btype="high", fs=fs, output="sos")
    hp4_output = sosfilt(hp4_sos, signal)
    write_sos(out, "SOSFILT_HP4_SOS", "butter(4, 5000, 'high', fs=44100)", hp4_sos)
    write_array(out, "SOSFILT_HP4_OUTPUT", "sosfilt(hp4_sos, signal)", hp4_output)

    # --- Case 3: Bandpass Butterworth order 4, fc=[1000, 5000] Hz ---
    bp4_sos = butter(4, [1000, 5000], btype="band", fs=fs, output="sos")
    bp4_output = sosfilt(bp4_sos, signal)
    write_sos(out, "SOSFILT_BP4_SOS", "butter(4, [1000, 5000], 'band', fs=44100)", bp4_sos)
    write_array(out, "SOSFILT_BP4_OUTPUT", "sosfilt(bp4_sos, signal)", bp4_output)

    # --- Case 4: Multi-block streaming (longer signal, same LP4) ---
    n_long = 1024
    t_long = np.arange(n_long) / fs
    long_signal = (
        np.sin(2 * np.pi * 400 * t_long)
        + 0.3 * np.sin(2 * np.pi * 2000 * t_long)
        + 0.2 * np.sin(2 * np.pi * 12000 * t_long)
    )
    long_output = sosfilt(lp4_sos, long_signal)
    write_array(
        out, "SOSFILT_LONG_INPUT",
        f"{n_long} samples: multi-tone at {fs:.0f} Hz",
        long_signal,
    )
    write_array(
        out, "SOSFILT_LONG_OUTPUT",
        "sosfilt(lp4_sos, long_signal) — same LP4 Butterworth",
        long_output,
    )


if __name__ == "__main__":
    main()
