#!/usr/bin/env python3
"""Generate scipy reference data for cross-correlation tests.

Outputs a Rust source file with const arrays for cross-correlation
test vectors, validated against scipy.signal.correlate.

Regenerate with: make gen-xcorr-reference

Requires: scipy, numpy
"""

import sys

import numpy as np
from scipy.signal import correlate


def format_f64(val):
    """Format one value as a Rust f64 literal."""
    return f"    {val:.17e},"


def write_array(out, name, arr, doc):
    """Write a const f64 array."""
    out.write(f"/// {doc}\n")
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write("    reason = \"scipy reference\"\n")
    out.write(")]\n")
    out.write(f"const {name}: &[f64] = &[\n")
    for val in arr:
        out.write(format_f64(val) + "\n")
    out.write("];\n\n")


def main():
    out = sys.stdout

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_xcorr_reference.py\n")
    out.write("// Regenerate: make gen-xcorr-reference\n")
    out.write("//\n")
    out.write(f"// scipy {__import__('scipy').__version__}, ")
    out.write(f"numpy {np.__version__}\n")
    out.write("\n")

    # ── Case 1: Short signals, asymmetric lengths ────────────────────
    # Exercises basic correctness with a small, verifiable example.
    rng = np.random.default_rng(42)
    a1 = rng.standard_normal(16)
    b1 = rng.standard_normal(8)
    r1 = correlate(a1, b1, mode="full")

    write_array(out, "XCORR_SHORT_A", a1, "Short test signal a (len=16)")
    write_array(out, "XCORR_SHORT_B", b1, "Short test signal b (len=8)")
    write_array(out, "XCORR_SHORT_RESULT", r1,
                f"`correlate(a, b, mode='full')` — len={len(r1)}")

    # ── Case 2: Equal-length signals (autocorrelation-like) ──────────
    # Both signals same length, different content.
    a2 = rng.standard_normal(32)
    b2 = rng.standard_normal(32)
    r2 = correlate(a2, b2, mode="full")

    write_array(out, "XCORR_EQUAL_A", a2, "Equal-length test signal a (len=32)")
    write_array(out, "XCORR_EQUAL_B", b2, "Equal-length test signal b (len=32)")
    write_array(out, "XCORR_EQUAL_RESULT", r2,
                f"`correlate(a, b, mode='full')` — len={len(r2)}")

    # ── Case 3: Sinusoidal signals — detect known delay ──────────────
    # a is a sine wave, b is the same sine shifted by `delay` samples.
    # The cross-correlation should peak near the true delay.
    n = 128
    delay = 17
    freq = 0.1  # cycles per sample
    t = np.arange(n, dtype=np.float64)
    a3 = np.sin(2.0 * np.pi * freq * t)
    b3 = np.sin(2.0 * np.pi * freq * (t - delay))
    r3 = correlate(a3, b3, mode="full")

    out.write(f"/// Delay detection: a = sin(2π·{freq}·t), "
              f"b = sin(2π·{freq}·(t-{delay})), len={n}\n")
    out.write(f"const XCORR_DELAY_N: usize = {n};\n")
    out.write(f"const XCORR_DELAY_TRUE_LAG: usize = {delay};\n\n")

    write_array(out, "XCORR_DELAY_A", a3, f"Sine wave, freq={freq} cycles/sample")
    write_array(out, "XCORR_DELAY_B", b3,
                f"Same sine delayed by {delay} samples")
    write_array(out, "XCORR_DELAY_RESULT", r3,
                f"`correlate(a, b, mode='full')` — len={len(r3)}")


if __name__ == "__main__":
    main()
