#!/usr/bin/env python3
"""Generate scipy reference data for polyphase resampling module tests.

Uses scipy.signal.upfirdn to produce expected output for known inputs
resampled through polyphase FIR with a specific prototype filter.

The Rust test injects the same prototype filter into the resampler via
a test-only constructor, then compares sample-by-sample.  This isolates
the polyphase algorithm from the filter design layer.

Regenerate with: make gen-resample-poly-reference

Requires: scipy, numpy
"""

import sys
from fractions import Fraction

import numpy as np
from scipy.signal import firwin, upfirdn


def format_value(val):
    """Format one value as a Rust f64 literal."""
    return f"    {val:.17e},"


def write_array(out, name, doc, values):
    """Write a const f64 array to the output."""
    out.write(f"/// `{doc}`\n")
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write('    reason = "scipy reference"\n')
    out.write(")]\n")
    out.write(f"pub const {name}: &[f64] = &[\n")
    for v in values:
        out.write(format_value(v) + "\n")
    out.write("];\n\n")


def write_scalar(out, name, doc, value):
    """Write a const usize to the output."""
    out.write(f"/// `{doc}`\n")
    out.write(f"pub const {name}: usize = {value};\n\n")


def gen_case(out, prefix, sr_in, sr_out, signal, doc_signal, num_taps=65):
    """Generate one upfirdn test case with a known prototype filter.

    Designs a lowpass prototype via firwin (matching our polyphase model),
    applies polyphase resampling via upfirdn, and emits:
      - L, M (rational factors)
      - prototype filter coefficients
      - input signal
      - expected output (truncated to our streaming output length)
    """
    ratio = Fraction(int(sr_out), int(sr_in))
    up = ratio.numerator
    down = ratio.denominator

    # Design the prototype: lowpass at 1/(2·max(L,M)) of the upsampled rate.
    # Use Hamming window to match typical OmniDSP usage.
    max_factor = max(up, down)
    # firwin cutoff is normalized to Nyquist (not sample rate),
    # so cutoff_norm = fc / (fs/2) = (1/(2*max_factor)) / 0.5 = 1/max_factor.
    cutoff_norm = 1.0 / max_factor
    # Clamp below 1.0 (Nyquist) for the passthrough case (L=M=1).
    cutoff_norm = min(cutoff_norm, 1.0 - 1e-8)

    h = firwin(num_taps, cutoff_norm, window="hamming")

    # upfirdn expects h scaled by L (same as our polyphase convention).
    output = upfirdn(h * up, signal, up, down)

    # Our streaming resampler produces ceil(N * L / M) samples, which
    # may be 1 more than upfirdn (upfirdn caps at the filter convolution
    # length).  Truncate to the shorter of the two.
    our_len = -(-len(signal) * up // down)  # ceil division
    out_len = min(our_len, len(output))
    output = output[:out_len]

    write_scalar(out, f"{prefix}_UP", f"L={up}", up)
    write_scalar(out, f"{prefix}_DOWN", f"M={down}", down)
    write_array(out, f"{prefix}_PROTO", f"firwin({num_taps}, hamming) prototype", h)
    write_array(out, f"{prefix}_INPUT", doc_signal, signal)
    write_array(out, f"{prefix}_OUTPUT", f"upfirdn(h*{up}, x, {up}, {down})[:{out_len}]", output)


def main():
    out = sys.stdout
    fs_44 = 44100.0
    fs_48 = 48000.0
    fs_22 = 22050.0

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_resample_poly_reference.py\n")
    out.write("// Regenerate: make gen-resample-poly-reference\n")
    out.write("//\n")
    out.write(f"// scipy {__import__('scipy').__version__}, ")
    out.write(f"numpy {np.__version__}\n")
    out.write("\n")

    # --- Deterministic input signals ---
    n = 256
    t44 = np.arange(n) / fs_44
    sig_44 = np.sin(2 * np.pi * 400 * t44) + 0.5 * np.sin(2 * np.pi * 8000 * t44)

    t48 = np.arange(n) / fs_48
    sig_48 = np.sin(2 * np.pi * 400 * t48) + 0.5 * np.sin(2 * np.pi * 8000 * t48)

    t22 = np.arange(n) / fs_22
    sig_22 = np.sin(2 * np.pi * 400 * t22) + 0.5 * np.sin(2 * np.pi * 4000 * t22)

    # --- Case 1: 44100 → 48000 (L=160, M=147) ---
    gen_case(
        out, "RPOLY_44_48", fs_44, fs_48, sig_44,
        f"{n} samples: sin(400 Hz) + 0.5*sin(8 kHz) at {fs_44:.0f} Hz",
    )

    # --- Case 2: 48000 → 44100 (L=147, M=160) ---
    gen_case(
        out, "RPOLY_48_44", fs_48, fs_44, sig_48,
        f"{n} samples: sin(400 Hz) + 0.5*sin(8 kHz) at {fs_48:.0f} Hz",
    )

    # --- Case 3: 44100 → 22050 (pure 2x decimation, L=1, M=2) ---
    gen_case(
        out, "RPOLY_44_22", fs_44, fs_22, sig_44,
        f"{n} samples at {fs_44:.0f} Hz",
    )

    # --- Case 4: 22050 → 44100 (pure 2x interpolation, L=2, M=1) ---
    gen_case(
        out, "RPOLY_22_44", fs_22, fs_44, sig_22,
        f"{n} samples: sin(400 Hz) + 0.5*sin(4 kHz) at {fs_22:.0f} Hz",
    )

    # --- Case 5: longer signal for streaming (44100 → 48000) ---
    n_long = 1024
    t_long = np.arange(n_long) / fs_44
    sig_long = (
        np.sin(2 * np.pi * 400 * t_long)
        + 0.3 * np.sin(2 * np.pi * 2000 * t_long)
        + 0.2 * np.sin(2 * np.pi * 12000 * t_long)
    )
    gen_case(
        out, "RPOLY_LONG", fs_44, fs_48, sig_long,
        f"{n_long} samples: multi-tone at {fs_44:.0f} Hz",
    )


if __name__ == "__main__":
    main()
