#!/usr/bin/env python3
"""Generate scipy reference data for FIR streaming filter tests.

Uses scipy.signal.lfilter to produce expected output for known inputs
filtered through FIR coefficients from firwin.

Outputs a Rust source file with const arrays of input signals and
expected outputs.

Regenerate with: make gen-fir-lfilter-reference

Requires: scipy, numpy
"""

import sys

import numpy as np
from scipy.signal import firwin, lfilter


def format_value(val):
    """Format one value as a Rust f64 literal."""
    return f"    {val:.17e},"


def write_array(out, name, doc, values):
    """Write a const array to the output."""
    out.write(f"/// `{doc}`\n")
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write('    reason = "scipy reference"\n')
    out.write(")]\n")
    out.write(f"const {name}: &[f64] = &[\n")
    for v in values:
        out.write(format_value(v) + "\n")
    out.write("];\n\n")


def main():
    out = sys.stdout
    fs = 44100.0

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_fir_lfilter_reference.py\n")
    out.write("// Regenerate: make gen-fir-lfilter-reference\n")
    out.write("//\n")
    out.write(f"// scipy {__import__('scipy').__version__}, ")
    out.write(f"numpy {np.__version__}\n")
    out.write("\n")

    # --- Deterministic input signal ---
    # Mix of two sinusoids: 400 Hz (passband for LP) + 8000 Hz (stopband for LP).
    n_samples = 256
    t = np.arange(n_samples) / fs
    signal = np.sin(2 * np.pi * 400 * t) + 0.5 * np.sin(2 * np.pi * 8000 * t)
    write_array(out, "LFILTER_INPUT", f"{n_samples} samples: sin(400 Hz) + 0.5*sin(8000 Hz) at {fs:.0f} Hz", signal)

    # --- Case 1: Lowpass order 30, Hamming, fc=1000 Hz ---
    lp_taps = firwin(31, 1000, window="hamming", pass_zero=True, fs=fs)
    lp_output = lfilter(lp_taps, 1.0, signal)
    write_array(out, "LFILTER_LP30_HAMMING_TAPS", "Lowpass order 30, Hamming, fc=1000 Hz", lp_taps)
    write_array(out, "LFILTER_LP30_HAMMING_OUTPUT", "lfilter(lp_taps, 1.0, signal)", lp_output)

    # --- Case 2: Highpass order 30, Hann, fc=10000 Hz ---
    hp_taps = firwin(31, 10000, window="hann", pass_zero=False, fs=fs)
    hp_output = lfilter(hp_taps, 1.0, signal)
    write_array(out, "LFILTER_HP30_HANN_TAPS", "Highpass order 30, Hann, fc=10000 Hz", hp_taps)
    write_array(out, "LFILTER_HP30_HANN_OUTPUT", "lfilter(hp_taps, 1.0, signal)", hp_output)

    # --- Case 3: Multi-block streaming (longer signal, same LP filter) ---
    n_long = 1024
    t_long = np.arange(n_long) / fs
    long_signal = (
        np.sin(2 * np.pi * 400 * t_long)
        + 0.3 * np.sin(2 * np.pi * 2000 * t_long)
        + 0.2 * np.sin(2 * np.pi * 12000 * t_long)
    )
    long_output = lfilter(lp_taps, 1.0, long_signal)
    write_array(out, "LFILTER_LONG_INPUT", f"{n_long} samples: multi-tone at {fs:.0f} Hz", long_signal)
    write_array(out, "LFILTER_LONG_OUTPUT", "lfilter(lp_taps, 1.0, long_signal) — same LP30 Hamming", long_output)


if __name__ == "__main__":
    main()
