#!/usr/bin/env python3
"""Generate librosa reference data for CQT integration tests.

Uses librosa.filters.wavelet to build CQT time-domain kernels — an
independent implementation of the windowed-sinusoid kernel construction.
We then FFT the kernels and compute a single-frame CQT via frequency-
domain correlation, matching our Rust algorithm exactly.

The independent variable is the kernel: librosa builds the windowed
complex sinusoid, we FFT + conjugate + correlate.  If our Rust code
produces the same magnitudes, the entire CQT pipeline is validated
against librosa's filter design.

Regenerate with: make gen-cqt-librosa-reference

Requires: librosa, numpy
"""

import sys
from math import ceil, log2

import numpy as np
import librosa


def format_f64(val):
    """Format one value as a Rust f64 literal."""
    return f"{val:.17e}"


def write_real_array(out, name, doc, values):
    """Write a const f64 array to the output."""
    out.write(f"/// {doc}\n")
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write('    reason = "librosa reference"\n')
    out.write(")]\n")
    out.write(f"const {name}: &[f64] = &[\n")
    for v in values:
        out.write(f"    {format_f64(v)},\n")
    out.write("];\n\n")


def main():
    out = sys.stdout

    sr = 44100.0
    fmin = 440.0
    fmax = 880.0
    bpo = 12

    n_bins = round(bpo * log2(fmax / fmin))

    # Parameters matching our Rust implementation.
    q = 1.0 / (2.0 ** (1.0 / bpo) - 1.0)
    max_kernel = ceil(q * sr / fmin)
    fft_length = 1 << ceil(log2(max_kernel))

    freqs = librosa.cqt_frequencies(n_bins=n_bins, fmin=fmin, bins_per_octave=bpo)

    # Get librosa's time-domain CQT wavelets (the replacement for
    # constant_q).  Each wavelet is a complex array of length N_k.
    # norm=None: no normalization applied to the wavelets.
    # librosa's default alpha uses a different formula than our Q.
    # Pass alpha = 2^(1/B) - 1 explicitly to match our Q = 1/alpha.
    alpha = 2.0 ** (1.0 / bpo) - 1.0

    # librosa hardcodes fftbins=True (periodic Hann) internally.
    # Pass a callable that returns a symmetric Hann to match our
    # Rust implementation which uses Window::from_fn (symmetric).
    from scipy.signal.windows import hann as scipy_hann

    def symmetric_hann(n):
        return scipy_hann(n, sym=True)

    wavelets, kernel_lengths = librosa.filters.wavelet(
        freqs=freqs, sr=sr, window=symmetric_hann, filter_scale=1,
        norm=None, gamma=0, alpha=alpha,
    )

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_cqt_librosa_reference.py\n")
    out.write("// Regenerate: make gen-cqt-librosa-reference\n")
    out.write("//\n")
    out.write(f"// librosa {librosa.__version__}, numpy {np.__version__}\n")
    out.write("//\n")
    out.write(f"// CQT: sr={sr}, fmin={fmin}, fmax={fmax}, B={bpo}\n")
    out.write(f"// Q={q:.10f}, {n_bins} bins, fft_length={fft_length}\n")
    out.write(f"// kernel_lengths={list(kernel_lengths)}\n")
    out.write("//\n")
    out.write("// Kernels from librosa.filters.wavelet (norm=None).\n")
    out.write("// Correlation: conj(FFT(kernel/N_k)) * FFT(signal) / N.\n")
    out.write("\n")

    out.write(f"const CQT_LIB_SAMPLE_RATE: f64 = {sr};\n")
    out.write(f"const CQT_LIB_MIN_FREQ: f64 = {fmin};\n")
    out.write(f"const CQT_LIB_MAX_FREQ: f64 = {fmax};\n")
    out.write(f"const CQT_LIB_BINS_PER_OCTAVE: u32 = {bpo};\n")
    out.write(f"const CQT_LIB_FFT_LENGTH: usize = {fft_length};\n")
    out.write(f"const CQT_LIB_NUM_BINS: usize = {n_bins};\n")
    out.write("\n")

    t = np.arange(fft_length) / sr

    # Build frequency-domain stored kernels from librosa's time-domain
    # wavelets, using our normalization convention:
    #   stored[k] = conj(FFT(wavelet[k] / N_k)) / N
    stored_kernels = []
    for k in range(n_bins):
        wav = wavelets[k]
        n_k = int(np.ceil(kernel_lengths[k]))
        # librosa's wavelet with pad_fft=True is already zero-padded
        # to fft_length.  Normalize by the true kernel length N_k.
        kernel_td = np.zeros(fft_length, dtype=complex)
        kernel_td[: len(wav)] = wav / n_k
        kernel_fd = np.fft.fft(kernel_td)
        stored = np.conj(kernel_fd) / fft_length
        stored_kernels.append(stored)

    def compute_cqt(signal):
        """Single-frame CQT using librosa's wavelets, our normalization."""
        X = np.fft.fft(signal, n=fft_length)
        coeffs = np.zeros(n_bins, dtype=complex)
        for k in range(n_bins):
            coeffs[k] = np.sum(X * stored_kernels[k])
        return np.abs(coeffs)

    # --- Case 1: Sum of all bin center frequencies ---
    all_tones = np.sum([np.sin(2 * np.pi * f * t) for f in freqs], axis=0)
    all_tones_mag = compute_cqt(all_tones)

    write_real_array(
        out, "CQT_LIB_ALL_TONES_INPUT",
        f"Sum of {n_bins} sines at all bin center frequencies ({fft_length} samples)",
        all_tones,
    )
    write_real_array(
        out, "CQT_LIB_ALL_TONES_MAG",
        "CQT magnitudes via librosa wavelet kernels",
        all_tones_mag,
    )

    # --- Case 2: Pure tone at middle bin ---
    mid_bin = n_bins // 2
    tone_freq = freqs[mid_bin]
    tone = np.sin(2 * np.pi * tone_freq * t)
    tone_mag = compute_cqt(tone)

    write_real_array(
        out, "CQT_LIB_TONE_INPUT",
        f"Pure sine at {tone_freq:.6f} Hz (bin {mid_bin}, {fft_length} samples)",
        tone,
    )
    write_real_array(
        out, "CQT_LIB_TONE_MAG",
        f"CQT magnitudes of sine at bin {mid_bin} (librosa kernels)",
        tone_mag,
    )
    out.write(f"const CQT_LIB_TONE_BIN: usize = {mid_bin};\n\n")

    # --- Case 3: Two tones at bin 2 and bin 9 ---
    freq_a = freqs[2]
    freq_b = freqs[9]
    two_tone = np.sin(2 * np.pi * freq_a * t) + np.sin(2 * np.pi * freq_b * t)
    two_tone_mag = compute_cqt(two_tone)

    write_real_array(
        out, "CQT_LIB_TWO_TONE_INPUT",
        f"Two sines at {freq_a:.6f} Hz (bin 2) and {freq_b:.6f} Hz (bin 9)",
        two_tone,
    )
    write_real_array(
        out, "CQT_LIB_TWO_TONE_MAG",
        "CQT magnitudes of two-tone signal (librosa kernels)",
        two_tone_mag,
    )


if __name__ == "__main__":
    main()
