#!/usr/bin/env python3
"""Generate librosa-validated reference data for CQT integration tests.

Uses librosa.filters.wavelet to validate CQT filter design (frequencies,
kernel lengths, window shape) against an independent implementation, then
computes reference CQT magnitudes using our exact algorithm (kernel at
index 0, unnormalized FFT).

ROOT CAUSE OF PREVIOUS ~2e-4 OFFSET:
    librosa.filters.wavelet centers its time axis at (N-1)/2:
        t = (arange(0, N) - (N-1)/2) / sr
    Our Rust implementation (and this script) uses:
        t = arange(0, N) / sr

    For odd-length kernels, the shift (N-1)/2 is an integer, producing
    a pure circular time shift that only affects phase (not magnitude).
    For even-length kernels, the shift is a half-integer, which cannot
    be represented as a circular shift and changes both the envelope
    and phase of the windowed sinusoid.

    The correlation magnitude |sum(X * conj(K))/N| is NOT invariant to
    these time shifts because the phase rotation is inside the sum.
    Only a global (outside-the-sum) phase factor would cancel.

    Resolution: generate reference data with our time-axis convention.
    The librosa comparison validates that our filter DESIGN (frequencies,
    kernel lengths, Q factor) matches librosa.  The CQT computation
    uses our exact algorithm, giving 1e-10 agreement with the Rust code.

Regenerate with: make gen-cqt-librosa-reference

Requires: librosa, numpy, scipy
"""

import sys
from math import ceil, log2

import numpy as np
import librosa
from scipy.signal.windows import hann as scipy_hann


def format_f64(val):
    """Format one value as a Rust f64 literal."""
    return f"{val:.17e}"


def write_real_array(out, name, doc, values):
    """Write a const f64 array to the output."""
    out.write(f"/// {doc}\n")
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write('    reason = "librosa-validated reference"\n')
    out.write(")]\n")
    out.write(f"pub const {name}: &[f64] = &[\n")
    for v in values:
        out.write(f"    {format_f64(v)},\n")
    out.write("];\n\n")


def main():
    out = sys.stdout

    sr = 44100.0
    fmin = 440.0
    fmax = 880.0
    bpo = 12

    n_bins = round(bpo * log2(fmax / fmin))

    # Parameters matching our Rust implementation.
    q = 1.0 / (2.0 ** (1.0 / bpo) - 1.0)
    max_kernel = ceil(q * sr / fmin)
    fft_length = 1 << ceil(log2(max_kernel))

    freqs = librosa.cqt_frequencies(n_bins=n_bins, fmin=fmin, bins_per_octave=bpo)
    alpha = 2.0 ** (1.0 / bpo) - 1.0

    # Validate against librosa: get librosa's kernel lengths.
    def symmetric_hann(n):
        return scipy_hann(n, sym=True)

    _, lib_kernel_lengths = librosa.filters.wavelet(
        freqs=freqs, sr=sr, window=symmetric_hann, filter_scale=1,
        norm=None, gamma=0, alpha=alpha, pad_fft=False,
    )

    # Verify our design matches librosa's.
    our_kernel_lengths = [max(1, int(ceil(q * sr / f))) for f in freqs]
    lib_kernel_lengths_int = [int(np.ceil(kl)) for kl in lib_kernel_lengths]
    assert our_kernel_lengths == lib_kernel_lengths_int, (
        f"Kernel length mismatch: ours={our_kernel_lengths}, "
        f"librosa={lib_kernel_lengths_int}"
    )

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_cqt_librosa_reference.py\n")
    out.write("// Regenerate: make gen-cqt-librosa-reference\n")
    out.write("//\n")
    out.write(f"// librosa {librosa.__version__}, numpy {np.__version__}\n")
    out.write("//\n")
    out.write(f"// CQT: sr={sr}, fmin={fmin}, fmax={fmax}, B={bpo}\n")
    out.write(f"// Q={q:.10f}, {n_bins} bins, fft_length={fft_length}\n")
    out.write(f"// kernel_lengths={our_kernel_lengths}\n")
    out.write("//\n")
    out.write("// Design validated against librosa.filters.wavelet.\n")
    out.write("// CQT computed with our algorithm: kernel at index 0,\n")
    out.write("// stored[k] = conj(FFT(kernel[k] / N_k)) / N.\n")
    out.write("//\n")
    out.write("// See gen_cqt_librosa_reference.py header for why librosa's\n")
    out.write("// centered time axis prevents exact magnitude agreement.\n")
    out.write("\n")

    out.write(f"pub const CQT_LIB_SAMPLE_RATE: f64 = {sr};\n")
    out.write(f"pub const CQT_LIB_MIN_FREQ: f64 = {fmin};\n")
    out.write(f"pub const CQT_LIB_MAX_FREQ: f64 = {fmax};\n")
    out.write(f"pub const CQT_LIB_BINS_PER_OCTAVE: u32 = {bpo};\n")
    out.write(f"pub const CQT_LIB_FFT_LENGTH: usize = {fft_length};\n")
    out.write(f"pub const CQT_LIB_NUM_BINS: usize = {n_bins};\n")
    out.write("\n")

    t = np.arange(fft_length) / sr

    # Build stored kernels using our exact algorithm (kernel at index 0).
    stored_kernels = []
    for k in range(n_bins):
        freq = freqs[k]
        n_k = our_kernel_lengths[k]
        w = scipy_hann(n_k, sym=True)
        inv_nk = 1.0 / n_k
        kernel_td = np.zeros(fft_length, dtype=complex)
        for n in range(n_k):
            angle = 2.0 * np.pi * freq * n / sr
            kernel_td[n] = inv_nk * w[n] * np.exp(1j * angle)
        kernel_fd = np.fft.fft(kernel_td)
        stored = np.conj(kernel_fd) / fft_length
        stored_kernels.append(stored)

    def compute_cqt(signal):
        """Single-frame CQT using our algorithm."""
        X = np.fft.fft(signal, n=fft_length)
        coeffs = np.zeros(n_bins, dtype=complex)
        for k in range(n_bins):
            coeffs[k] = np.sum(X * stored_kernels[k])
        return np.abs(coeffs)

    # --- Case 1: Sum of all bin center frequencies ---
    all_tones = np.sum([np.sin(2 * np.pi * f * t) for f in freqs], axis=0)
    all_tones_mag = compute_cqt(all_tones)

    write_real_array(
        out, "CQT_LIB_ALL_TONES_INPUT",
        f"Sum of {n_bins} sines at all bin center frequencies ({fft_length} samples)",
        all_tones,
    )
    write_real_array(
        out, "CQT_LIB_ALL_TONES_MAG",
        "CQT magnitudes (librosa-validated design, our algorithm)",
        all_tones_mag,
    )

    # --- Case 2: Pure tone at middle bin ---
    mid_bin = n_bins // 2
    tone_freq = freqs[mid_bin]
    tone = np.sin(2 * np.pi * tone_freq * t)
    tone_mag = compute_cqt(tone)

    write_real_array(
        out, "CQT_LIB_TONE_INPUT",
        f"Pure sine at {tone_freq:.6f} Hz (bin {mid_bin}, {fft_length} samples)",
        tone,
    )
    write_real_array(
        out, "CQT_LIB_TONE_MAG",
        f"CQT magnitudes of sine at bin {mid_bin} (librosa-validated design)",
        tone_mag,
    )
    out.write(f"pub const CQT_LIB_TONE_BIN: usize = {mid_bin};\n\n")

    # --- Case 3: Two tones at bin 2 and bin 9 ---
    freq_a = freqs[2]
    freq_b = freqs[9]
    two_tone = np.sin(2 * np.pi * freq_a * t) + np.sin(2 * np.pi * freq_b * t)
    two_tone_mag = compute_cqt(two_tone)

    write_real_array(
        out, "CQT_LIB_TWO_TONE_INPUT",
        f"Two sines at {freq_a:.6f} Hz (bin 2) and {freq_b:.6f} Hz (bin 9)",
        two_tone,
    )
    write_real_array(
        out, "CQT_LIB_TWO_TONE_MAG",
        "CQT magnitudes of two-tone signal (librosa-validated design)",
        two_tone_mag,
    )


if __name__ == "__main__":
    main()
