#!/usr/bin/env python3
"""Generate scipy reference data for resampling prototype filter tests.

Outputs a Rust source file with const arrays of L, M, and prototype filter
coefficients for standard sample rate conversions.
Regenerate with: make gen-resample-reference

Requires: scipy, numpy
"""

import sys
from math import gcd

import numpy as np
from scipy.signal import firwin


def quality_params(quality, quality_max=10):
    """Mirror the Rust quality_params function."""
    t = quality / quality_max
    attenuation_db = t * 80.0 + 40.0
    transition_fraction = t * -0.35 + 0.45
    return attenuation_db, transition_fraction


def design_resample(sr_in, sr_out, quality):
    """Design a resampling prototype filter matching the Rust implementation."""
    in_int = round(sr_in)
    out_int = round(sr_out)
    g = gcd(out_int, in_int)
    up = out_int // g
    down = in_int // g

    max_factor = max(up, down)
    cutoff_normalized = min(1.0 / (2.0 * max_factor), 0.5 - 1e-8)

    attenuation_db, transition_fraction = quality_params(quality)
    delta_f = cutoff_normalized * transition_fraction

    order_est = (attenuation_db - 7.95) / (2.285 * 2.0 * np.pi * delta_f)
    order = max(16, min(4096, int(np.ceil(order_est))))
    if order % 2 != 0:
        order = min(order + 1, 4096)

    num_taps = order + 1
    upsampled_rate = up * sr_in
    cutoff_hz = cutoff_normalized * upsampled_rate

    # Use scipy.signal.firwin for the reference filter
    taps = firwin(num_taps, cutoff_hz, fs=upsampled_rate, window="hamming")

    return up, down, order, taps


# (name, sr_in, sr_out, quality)
CASES = [
    # Small ratios (short filters)
    ("RESAMPLE_44100_22050_Q5",  44100, 22050, 5),
    ("RESAMPLE_22050_44100_Q5",  22050, 44100, 5),
    ("RESAMPLE_44100_44100_Q5",  44100, 44100, 5),
    ("RESAMPLE_48000_16000_Q3",  48000, 16000, 3),
    ("RESAMPLE_16000_48000_Q3",  16000, 48000, 3),
    # Large ratios (long filters, hit 4096 cap at higher quality)
    ("RESAMPLE_44100_48000_Q0",  44100, 48000, 0),
    ("RESAMPLE_44100_48000_Q5",  44100, 48000, 5),
    ("RESAMPLE_48000_44100_Q5",  48000, 44100, 5),
]


def main():
    out = sys.stdout

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_resample_reference.py\n")
    out.write("// Regenerate: make gen-resample-reference\n")
    out.write("//\n")
    out.write(f"// scipy {__import__('scipy').__version__}, ")
    out.write(f"numpy {np.__version__}\n")
    out.write("\n")

    for name, sr_in, sr_out, quality in CASES:
        up, down, order, taps = design_resample(sr_in, sr_out, quality)

        out.write(f"/// Resample {sr_in} -> {sr_out}, quality={quality}\n")
        out.write(f"/// L={up}, M={down}, order={order}, taps={len(taps)}\n")
        out.write(f"const {name}_UP: usize = {up};\n")
        out.write(f"const {name}_DOWN: usize = {down};\n")
        out.write(f"const {name}_ORDER: usize = {order};\n")
        out.write("#[allow(\n")
        out.write("    clippy::excessive_precision,\n")
        out.write("    clippy::unreadable_literal,\n")
        out.write("    reason = \"scipy reference\"\n")
        out.write(")]\n")
        out.write(f"const {name}_TAPS: &[f64] = &[\n")
        for t in taps:
            out.write(f"    {t:.17e},\n")
        out.write("];\n\n")


if __name__ == "__main__":
    main()
