#!/usr/bin/env python3
"""Generate numpy reference data for CQT design tests.

Outputs a Rust source file with const arrays of Q, frequencies, kernel lengths,
FFT length, and hop length for standard CQT configurations.
Regenerate with: make gen-cqt-reference

Requires: numpy
"""

import sys
from math import ceil, log2

import numpy as np


def design_cqt(sample_rate, min_freq, max_freq, bins_per_octave):
    """Design CQT parameters matching the Rust implementation."""
    b = bins_per_octave
    nyquist = sample_rate / 2.0

    # Q = 1 / (2^(1/B) - 1)
    q = 1.0 / (2.0 ** (1.0 / b) - 1.0)

    # Generate bins
    freqs = []
    kernel_lengths = []
    k = 0
    while True:
        freq = min_freq * 2.0 ** (k / b)
        if freq >= max_freq or freq >= nyquist:
            break
        kernel_len = max(1, int(ceil(q * sample_rate / freq)))
        freqs.append(freq)
        kernel_lengths.append(kernel_len)
        k += 1

    # FFT length: next power of two >= longest kernel
    max_kernel = kernel_lengths[0]
    fft_length = 1 << int(ceil(log2(max_kernel))) if max_kernel > 0 else 1

    # Hop length: based on shortest kernel
    min_kernel = kernel_lengths[-1]
    hop_length = max(1, min_kernel // 4)

    return q, freqs, kernel_lengths, fft_length, hop_length


# (prefix, sample_rate, min_freq, max_freq, bins_per_octave)
CASES = [
    # Standard music analysis: piano range, 24 bins/octave
    ("CQT_PIANO_24", 44100.0, 27.5, 4186.0, 24),
    # Narrow range: one octave (440-880 Hz), 12 bins/octave
    ("CQT_OCTAVE_12", 44100.0, 440.0, 880.0, 12),
    # Edge case: max_freq near Nyquist
    ("CQT_NYQUIST_12", 44100.0, 10000.0, 22000.0, 12),
]


def main():
    out = sys.stdout

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_cqt_reference.py\n")
    out.write("// Regenerate: make gen-cqt-reference\n")
    out.write("//\n")
    out.write(f"// numpy {np.__version__}\n")
    out.write("\n")

    for prefix, sr, fmin, fmax, bpo in CASES:
        q, freqs, kernel_lengths, fft_length, hop_length = design_cqt(
            sr, fmin, fmax, bpo
        )

        out.write(f"/// CQT design: sr={sr}, fmin={fmin}, fmax={fmax}, B={bpo}\n")
        out.write(f"/// Q={q:.10f}, {len(freqs)} bins, ")
        out.write(f"fft={fft_length}, hop={hop_length}\n")
        out.write(f"const {prefix}_SAMPLE_RATE: f64 = {sr};\n")
        out.write(f"const {prefix}_MIN_FREQ: f64 = {fmin};\n")
        out.write(f"const {prefix}_MAX_FREQ: f64 = {fmax};\n")
        out.write(f"const {prefix}_BINS_PER_OCTAVE: u32 = {bpo};\n")
        out.write("#[allow(\n")
        out.write("    clippy::excessive_precision,\n")
        out.write("    clippy::unreadable_literal,\n")
        out.write('    reason = "numpy reference"\n')
        out.write(")]\n")
        out.write(f"const {prefix}_Q: f64 = {q:.17e};\n")
        out.write(f"const {prefix}_FFT_LENGTH: usize = {fft_length};\n")
        out.write(f"const {prefix}_HOP_LENGTH: usize = {hop_length};\n")

        out.write("#[allow(\n")
        out.write("    clippy::excessive_precision,\n")
        out.write("    clippy::unreadable_literal,\n")
        out.write('    reason = "numpy reference"\n')
        out.write(")]\n")
        out.write(f"const {prefix}_FREQS: &[f64] = &[\n")
        for f in freqs:
            out.write(f"    {f:.17e},\n")
        out.write("];\n")

        out.write(f"const {prefix}_KERNEL_LENGTHS: &[usize] = &[\n")
        for kl in kernel_lengths:
            out.write(f"    {kl},\n")
        out.write("];\n\n")


if __name__ == "__main__":
    main()
