#!/usr/bin/env python3
"""Generate scipy reference data for DCT tests.

Outputs a Rust source file with const arrays of DCT-II and DCT-III
results for various input signals, lengths, and normalization modes.

Regenerate with: make gen-dct-reference

Requires: scipy, numpy
"""

import sys

import numpy as np
from scipy.fft import dct


def format_f64(val):
    """Format one value as a Rust f64 literal."""
    return f"    {val:.17e},"


def write_array(out, name, values):
    """Write a const &[f64] array."""
    out.write("#[allow(\n")
    out.write("    clippy::excessive_precision,\n")
    out.write("    clippy::unreadable_literal,\n")
    out.write('    reason = "scipy reference"\n')
    out.write(")]\n")
    out.write(f"const {name}: &[f64] = &[\n")
    for v in values:
        out.write(format_f64(v) + "\n")
    out.write("];\n\n")


# Test cases: (name_suffix, input, description)
INPUTS = [
    ("RAMP8", np.arange(1, 9, dtype=float), "ramp [1..8]"),
    ("SINE16", np.sin(np.arange(16) * 0.7), "sin(0.7*n), N=16"),
    ("COS17", np.cos(np.arange(17) * 1.3), "cos(1.3*n), N=17 (non-power-of-two)"),
    ("RANDOM64", None, "seeded random, N=64"),  # generated below
]


def main():
    out = sys.stdout

    # Generate seeded random signal
    rng = np.random.default_rng(42)
    random64 = rng.standard_normal(64)

    # Patch into INPUTS
    inputs = []
    for name, arr, desc in INPUTS:
        if arr is None:
            inputs.append((name, random64, desc))
        else:
            inputs.append((name, arr, desc))

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_dct_reference.py\n")
    out.write("// Regenerate: make gen-dct-reference\n")
    out.write("//\n")
    out.write(f"// scipy {__import__('scipy').__version__}, ")
    out.write(f"numpy {np.__version__}\n")
    out.write("\n")

    for name, signal, desc in inputs:
        n = len(signal)
        out.write(f"// --- {desc} (N={n}) ---\n\n")

        # Write the input signal
        write_array(out, f"DCT_INPUT_{name}", signal)

        # DCT-II unnormalized
        result = dct(signal, type=2, norm=None)
        write_array(out, f"DCT2_{name}", result)

        # DCT-II orthonormal
        result = dct(signal, type=2, norm="ortho")
        write_array(out, f"DCT2_ORTHO_{name}", result)

        # DCT-III unnormalized
        result = dct(signal, type=3, norm=None)
        write_array(out, f"DCT3_{name}", result)

        # DCT-III orthonormal
        result = dct(signal, type=3, norm="ortho")
        write_array(out, f"DCT3_ORTHO_{name}", result)


if __name__ == "__main__":
    main()
