#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Two Wells <contact@twowells.dev>

"""Generate Hilbert transform reference data from scipy.signal.hilbert."""

import sys

import numpy as np
from scipy.signal import hilbert


def format_f64_array(name: str, arr: np.ndarray) -> str:
    """Format a 1-D array as a Rust const slice."""
    values = ", ".join(f"{x:.17e}" for x in arr)
    return f"const {name}: &[f64] = &[{values}];"


def format_complex_array(name: str, arr: np.ndarray) -> str:
    """Format a 1-D complex array as a Rust const slice of (re, im) tuples."""
    values = ", ".join(f"({x.real:.17e}, {x.imag:.17e})" for x in arr)
    return f"const {name}: &[(f64, f64)] = &[{values}];"


def main():
    lines = []
    lines.append("// Auto-generated by scripts/gen_hilbert_reference.py")
    lines.append("// Do not edit manually.")
    lines.append("")

    # Test 1: Chirp signal (linear sweep 100-1000 Hz, N=256, sr=8000)
    n1 = 256
    sr1 = 8000.0
    t1 = np.arange(n1) / sr1
    f0, f1_hz = 100.0, 1000.0
    chirp = np.cos(2 * np.pi * (f0 * t1 + (f1_hz - f0) / (2 * t1[-1]) * t1**2))
    z1 = hilbert(chirp)

    lines.append(format_f64_array("CHIRP_INPUT", chirp))
    lines.append(format_complex_array("CHIRP_EXPECTED", z1))
    lines.append("")

    # Test 2: Sum of two sinusoids (440 Hz + 880 Hz, N=512, sr=44100)
    n2 = 512
    sr2 = 44100.0
    t2 = np.arange(n2) / sr2
    two_tones = 0.7 * np.sin(2 * np.pi * 440.0 * t2) + 0.3 * np.cos(2 * np.pi * 880.0 * t2)
    z2 = hilbert(two_tones)

    lines.append(format_f64_array("TWO_TONES_INPUT", two_tones))
    lines.append(format_complex_array("TWO_TONES_EXPECTED", z2))
    lines.append("")

    # Test 3: Random signal (fixed seed, N=128)
    rng = np.random.default_rng(42)
    random_signal = rng.standard_normal(128)
    z3 = hilbert(random_signal)

    lines.append(format_f64_array("RANDOM_INPUT", random_signal))
    lines.append(format_complex_array("RANDOM_EXPECTED", z3))
    lines.append("")

    # Test functions
    lines.append("""
#[test]
fn scipy_chirp() {
    let factory = make_factory();
    let spec = HilbertSpec::<f64>::new(CHIRP_INPUT.len());
    let plan = factory.create_plan(&spec).expect("plan creation should succeed");

    let mut output = vec![Complex::new(0.0, 0.0); CHIRP_INPUT.len()];
    plan.process(CHIRP_INPUT, &mut output).expect("process should succeed");

    let tol = 1e-10;
    for (i, (z, &(re, im))) in output.iter().zip(CHIRP_EXPECTED).enumerate() {
        assert!(
            (z.re - re).abs() < tol,
            "chirp real mismatch at {i}: got {}, expected {re}",
            z.re
        );
        assert!(
            (z.im - im).abs() < tol,
            "chirp imag mismatch at {i}: got {}, expected {im}",
            z.im
        );
    }
}

#[test]
fn scipy_two_tones() {
    let factory = make_factory();
    let spec = HilbertSpec::<f64>::new(TWO_TONES_INPUT.len());
    let plan = factory.create_plan(&spec).expect("plan creation should succeed");

    let mut output = vec![Complex::new(0.0, 0.0); TWO_TONES_INPUT.len()];
    plan.process(TWO_TONES_INPUT, &mut output).expect("process should succeed");

    let tol = 1e-10;
    for (i, (z, &(re, im))) in output.iter().zip(TWO_TONES_EXPECTED).enumerate() {
        assert!(
            (z.re - re).abs() < tol,
            "two_tones real mismatch at {i}: got {}, expected {re}",
            z.re
        );
        assert!(
            (z.im - im).abs() < tol,
            "two_tones imag mismatch at {i}: got {}, expected {im}",
            z.im
        );
    }
}

#[test]
fn scipy_random() {
    let factory = make_factory();
    let spec = HilbertSpec::<f64>::new(RANDOM_INPUT.len());
    let plan = factory.create_plan(&spec).expect("plan creation should succeed");

    let mut output = vec![Complex::new(0.0, 0.0); RANDOM_INPUT.len()];
    plan.process(RANDOM_INPUT, &mut output).expect("process should succeed");

    let tol = 1e-10;
    for (i, (z, &(re, im))) in output.iter().zip(RANDOM_EXPECTED).enumerate() {
        assert!(
            (z.re - re).abs() < tol,
            "random real mismatch at {i}: got {}, expected {re}",
            z.re
        );
        assert!(
            (z.im - im).abs() < tol,
            "random imag mismatch at {i}: got {}, expected {im}",
            z.im
        );
    }
}""")

    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
