#!/usr/bin/env python3
"""Generate scipy reference data for equiripple (Parks-McClellan/Remez) FIR tests.

Outputs a Rust source file with const arrays of FIR tap coefficients computed by
`scipy.signal.remez`, one per case. These are the *independent* golden vectors the
OmniDSP equiripple design layer is validated against.
Regenerate with: make gen-remez-reference

Unit / weight convention (must match design/fir.rs `FirMethod::Equiripple`):

  * `pass_ripple` is the passband ripple in dB (peak deviation `Ap`), converted to
    a linear deviation  delta_p = (10**(Ap/20) - 1) / (10**(Ap/20) + 1).
  * `stop_atten` is the stopband attenuation in positive dB (`As`), converted to a
    linear deviation  delta_s = 10**(-As/20).
  * Desired band gains are 1 in each passband and 0 in each stopband.
  * Band weights equalise the realised ripple to the requested deviations and are
    therefore inversely proportional to them: a single common scale is irrelevant
    to remez, so we use  W_pass = 1/delta_p,  W_stop = 1/delta_s.

Requires: scipy, numpy
"""

import sys

import numpy as np
from scipy.signal import remez


def deltas(pass_ripple_db, stop_atten_db):
    """Linear passband / stopband deviations from the dB specs."""
    ap = 10.0 ** (pass_ripple_db / 20.0)
    delta_p = (ap - 1.0) / (ap + 1.0)
    delta_s = 10.0 ** (-stop_atten_db / 20.0)
    return delta_p, delta_s


def lowpass(numtaps, fpass, fstop, pass_ripple_db, stop_atten_db, fs):
    """Equiripple lowpass: pass [0, fpass], stop [fstop, fs/2]."""
    delta_p, delta_s = deltas(pass_ripple_db, stop_atten_db)
    bands = [0.0, fpass, fstop, fs / 2.0]
    desired = [1.0, 0.0]
    weight = [1.0 / delta_p, 1.0 / delta_s]
    return remez(numtaps, bands, desired, weight=weight, fs=fs)


def bandpass(numtaps, edges, pass_ripple_db, stop_atten_db, fs):
    """Equiripple bandpass: stop / pass / stop over the four-edge band layout.

    `edges` = [stop1_hi, pass_lo, pass_hi, stop2_lo] gives bands
    [0, stop1_hi] (stop), [pass_lo, pass_hi] (pass), [stop2_lo, fs/2] (stop).
    """
    delta_p, delta_s = deltas(pass_ripple_db, stop_atten_db)
    bands = [0.0, edges[0], edges[1], edges[2], edges[3], fs / 2.0]
    desired = [0.0, 1.0, 0.0]
    weight = [1.0 / delta_s, 1.0 / delta_p, 1.0 / delta_s]
    return remez(numtaps, bands, desired, weight=weight, fs=fs)


def halfband(numtaps, transition, stop_atten_db, fs):
    """Half-band lowpass at cutoff fs/4 with symmetric transition.

    pass [0, fs/4 - transition], stop [fs/4 + transition, fs/2]. A true half-band
    has its even-indexed taps (bar the center) equal to zero; scipy.signal.remez
    designed with symmetric bands and equal pass/stop weight yields that to
    numerical precision, which is exactly what we validate.
    """
    quarter = fs / 4.0
    bands = [0.0, quarter - transition, quarter + transition, fs / 2.0]
    desired = [1.0, 0.0]
    # Symmetric (pass == stop) weighting is what makes alternate taps vanish.
    weight = [1.0, 1.0]
    return remez(numtaps, bands, desired, weight=weight, fs=fs)


# (name, kind, params...) — see the matching builders above.
CASES = [
    # General lowpass: pass to 4 kHz, stop from 6 kHz, 0.1 dB / 60 dB.
    ("LP_REMEZ_4K_6K", "lp", 65, 4000.0, 6000.0, 0.1, 60.0, 44100.0),
    # General bandpass: pass 4-8 kHz, stops below 2 kHz and above 10 kHz.
    ("BP_REMEZ_4K_8K", "bp", 81, [2000.0, 4000.0, 8000.0, 10000.0], 0.1, 60.0, 44100.0),
    # Half-band x2 decimation: cutoff fs/4, odd length (Type I), alternate taps zero.
    ("HB_REMEZ_X2", "hb", 31, 0.1 * 44100.0, 70.0, 44100.0),
]


def main():
    out = sys.stdout

    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Two Wells <contact@twowells.dev>\n")
    out.write("\n")
    out.write("// Auto-generated by scripts/gen_remez_reference.py\n")
    out.write("// Regenerate: make gen-remez-reference\n")
    out.write("//\n")
    out.write(f"// scipy {__import__('scipy').__version__}, ")
    out.write(f"numpy {np.__version__}\n")
    out.write("\n")

    for case in CASES:
        name, kind = case[0], case[1]
        if kind == "lp":
            _, _, numtaps, fpass, fstop, ap, as_, fs = case
            taps = lowpass(numtaps, fpass, fstop, ap, as_, fs)
            doc = (
                f"remez({numtaps}, [0, {fpass}, {fstop}, {fs / 2}], [1, 0], "
                f"weighted; Ap={ap} dB, As={as_} dB, fs={fs}"
            )
        elif kind == "bp":
            _, _, numtaps, edges, ap, as_, fs = case
            taps = bandpass(numtaps, edges, ap, as_, fs)
            doc = (
                f"remez({numtaps}, [0, {edges[0]}, {edges[1]}, {edges[2]}, "
                f"{edges[3]}, {fs / 2}], [0, 1, 0], weighted; Ap={ap} dB, "
                f"As={as_} dB, fs={fs}"
            )
        elif kind == "hb":
            _, _, numtaps, transition, as_, fs = case
            taps = halfband(numtaps, transition, as_, fs)
            doc = (
                f"half-band remez({numtaps}, cutoff fs/4, transition={transition}, "
                f"As={as_} dB, fs={fs}); alternate taps ~ 0"
            )
        else:
            raise ValueError(f"unknown case kind {kind!r}")

        out.write(f"/// `{doc}`\n")
        out.write("#[allow(\n")
        out.write("    clippy::excessive_precision,\n")
        out.write("    clippy::unreadable_literal,\n")
        out.write("    reason = \"scipy reference\"\n")
        out.write(")]\n")
        out.write(f"pub const {name}: &[f64] = &[\n")
        for coeff in taps:
            out.write(f"    {coeff:.17e},\n")
        out.write("];\n\n")


if __name__ == "__main__":
    main()
